version: "3.5"

services:

    selenium:
        build:
            context: .
            args:
                - USER
                - UID
        image: loblab/selenium:debian
        hostname: selenium
        container_name: loblab-selenium
        restart: "always"
        environment:
            PYTHONIOENCODING: utf-8
            #http_proxy: socks5://proxy.loblab:1080
            #https_proxy: socks5://proxy.loblab:1080
        stdin_open: true
        tty: true
        volumes:
            - "/var/log/loblab/selenium:/var/log/selenium"
            - ".:/noip-renew"

